---
- name: Install containerd
  block:
    - name: Install containerd package
      ansible.builtin.package:
        name: containerd
        state: present
    - name: Enable and start containerd
      ansible.builtin.service:
        name: containerd
        enabled: true
        state: started
