---
- name: Install containerd
  block:
    - name: Install containerd package
      package:
        name: containerd
        state: present
    - name: Enable and start containerd
      service:
        name: containerd
        enabled: true
        state: started
