---
- name: Install CNI plugin
  when: cni == 'calico'
  block:
    - name: Apply Calico manifest
      ansible.builtin.command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      args:
        chdir: /tmp
      changed_when: false
