---
- name: Cleanup cluster
  hosts: all
  become: true
  tasks:
    - name: Reset kubeadm
      ansible.builtin.command: kubeadm reset -f
      changed_when: false
    - name: Remove kubernetes packages
      ansible.builtin.package:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: absent
    - name: Remove containerd packages
      ansible.builtin.package:
        name: containerd
        state: absent
    - name: Clean CNI
      ansible.builtin.file:
        path: /etc/cni
        state: absent
