---
- hosts: all
  become: true
  tasks:
    - name: Reset kubeadm
      command: kubeadm reset -f
    - name: Remove kubernetes packages
      package:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: absent
    - name: Remove containerd packages
      package:
        name: containerd
        state: absent
    - name: Clean CNI
      file:
        path: /etc/cni
        state: absent
