---
- name: Upgrade cluster
  hosts: all
  become: true
  tasks:
    - name: Upgrade kubeadm
      ansible.builtin.apt:
        name: kubeadm={{ kube_version }}-00
        state: present
      when: ansible_os_family == 'Debian'
    - name: Upgrade kubeadm (yum)
      ansible.builtin.dnf:
        name: kubeadm-{{ kube_version }}
        state: present
      when: ansible_os_family == 'RedHat'
    - name: Drain node
      ansible.builtin.command: >-
        kubeadm drain {{ inventory_hostname }} --ignore-daemonsets --delete-emptydir-data
      failed_when: false
      changed_when: false
    - name: Upgrade node
      ansible.builtin.command: kubeadm upgrade node
      changed_when: false
    - name: Uncordon node
      ansible.builtin.command: kubeadm uncordon {{ inventory_hostname }}
      changed_when: false
