---
- name: Install Kubernetes packages
  block:
    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
      when: ansible_os_family == 'Debian'
    - name: Add yum repository
      ansible.builtin.yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
        gpgcheck: 1
        repo_gpgcheck: 1
        enabled: 1
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
      when: ansible_os_family == 'RedHat'
    - name: Install packages
      ansible.builtin.package:
        name:
          - kubeadm-{{ kube_version }}*
          - kubelet-{{ kube_version }}*
          - kubectl-{{ kube_version }}*
        state: present
